### Register

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "admin",
    "username": "admin",
    "password": "baodeptrai199"
}

### Admin Create Multiple User

POST http://localhost:5000/api/admin/create-multiple-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzVhYTE2NmUyNGExN2I3YWM2MjEzYzYiLCJpYXQiOjE2NjY4ODM5NzN9.BBPuM2hSjtLKwOF-iKKmfsxijU61Pdl2x4mh1omE55Q
Content-Type: application/json

{
    "name": "Nguyen Hoang Bao",
    "username": "bao",
    "password": "bao",
    "start": 1,
    "end": 50
}

### Admin Delete Multiple User

DELETE http://localhost:5000/api/admin/delete-multiple-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzQ1MTc1ZDc5Y2Q4OGMzM2IzODQ2NzAiLCJpYXQiOjE2NjU0NzM0MjZ9.iLV27EQLoH0kZOWrXhafui1H8FMP2CtT-mpX2ronQHg

### Login

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "admin",
    "password": "baodeptrai199"
}

### Check token

GET http://localhost:5000/api/auth/check-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzM5NTE4MmNjYjE0NDJiYzhhMGQzOTMiLCJpYXQiOjE2NjQ3MDA4MDJ9.WoDthYDh15aSLBH-eiag2lRBBN7WB9QAN4KbNiPKq60

### Update user

PATCH  http://localhost:5000/api/auth/update-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzM5NTE4MmNjYjE0NDJiYzhhMGQzOTMiLCJpYXQiOjE2NjQ3MDA4MDJ9.WoDthYDh15aSLBH-eiag2lRBBN7WB9QAN4KbNiPKq60
Content-Type: application/json

{
    "name": "Nguyễn Hoàng Bảo",
    "username": "bao1",
    "password": "bao",
    "newPassword": "bao"
}

### Search user

GET http://localhost:5000/api/auth/search-user/text=i

### Create post

POST http://localhost:5000/api/post/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzQ0MzJhMWMyOTE0ODI2YzgxY2RmMjciLCJpYXQiOjE2NjU0NjA3MTl9.irueBwEj4Z4MNFo_VZM863tLbxOjEQSnwnX9O-0W0c8
Content-Type: application/json

{
    "content": "hello mọi người"
}

### Delete post

DELETE http://localhost:5000/api/post/delete/6342ea09537d752e04e50cf2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzNlZWU5NTNkNTJlOGIyMzVlZWUxMmYiLCJpYXQiOjE2NjUyMzU3NTV9.ZrgsIDYA6x3oBCYvLqKMUdzq3DTp0NqvVoyWU3yAtlc

### Like post

PUT http://localhost:5000/api/post/like-post/6342ea09537d752e04e50cf2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzNlZWU5NTNkNTJlOGIyMzVlZWUxMmYiLCJpYXQiOjE2NjUyMzU3NTV9.ZrgsIDYA6x3oBCYvLqKMUdzq3DTp0NqvVoyWU3yAtlc

### Unlike post

PUT http://localhost:5000/api/post/unlike-post/6342ea09537d752e04e50cf2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzNlZWU5NTNkNTJlOGIyMzVlZWUxMmYiLCJpYXQiOjE2NjUyMzU3NTV9.ZrgsIDYA6x3oBCYvLqKMUdzq3DTp0NqvVoyWU3yAtlc

### Add comment

PUT http://localhost:5000/api/post/add-comment/6342ea09537d752e04e50cf2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzNlZWU5NTNkNTJlOGIyMzVlZWUxMmYiLCJpYXQiOjE2NjUyMzU3NTV9.ZrgsIDYA6x3oBCYvLqKMUdzq3DTp0NqvVoyWU3yAtlc
Content-Type: application/json

{
    "text": "đasa"
}

### Remove comment

PUT http://localhost:5000/api/post/remove-comment/6342ea09537d752e04e50cf2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzNlZWU5NTNkNTJlOGIyMzVlZWUxMmYiLCJpYXQiOjE2NjUyMzU3NTV9.ZrgsIDYA6x3oBCYvLqKMUdzq3DTp0NqvVoyWU3yAtlc
Content-Type: application/json

{
    "commentId": "6342eb77317e22cfe708cdac"
}

### Total post

GET http://localhost:5000/api/post/total-post

### Get all posts

GET http://localhost:5000/api/post/all-post?page=1&perpage=10

### Admin Create Multiple Post

POST http://localhost:5000/api/admin/create-multiple-post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzVhYTE2NmUyNGExN2I3YWM2MjEzYzYiLCJpYXQiOjE2NjY4ODM5NzN9.BBPuM2hSjtLKwOF-iKKmfsxijU61Pdl2x4mh1omE55Q
Content-Type: application/json

{
    "content": "post",
    "start": 1,
    "end": 50
}

### Send message

PUT http://localhost:5000/api/message/send-message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzQ1MTc1ZDc5Y2Q4OGMzM2IzODQ2NzAiLCJpYXQiOjE2NjYzNjkyMzF9.ofFQOt9b8p9PTIazq7cmM11G6eMiVfle4fdMNrIqwp0
Content-Type: application/json

{
    "messagesId": "6352c534fdc3c1bef13f12ce",
    "receiveId": ["63451dc13fda9c771a2fa18e"],
    "text": "HAha"
}