POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "name": "Nguyễn Hoàng Bảo",
    "username": "bao1",
    "password": "bao"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "bao1",
    "password": "bao"
}

###

GET http://localhost:5000/api/auth/check-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzM5NTE4MmNjYjE0NDJiYzhhMGQzOTMiLCJpYXQiOjE2NjQ3MDA4MDJ9.WoDthYDh15aSLBH-eiag2lRBBN7WB9QAN4KbNiPKq60

###

PATCH  http://localhost:5000/api/auth/update-user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzM5NTE4MmNjYjE0NDJiYzhhMGQzOTMiLCJpYXQiOjE2NjQ3MDA4MDJ9.WoDthYDh15aSLBH-eiag2lRBBN7WB9QAN4KbNiPKq60
Content-Type: application/json

{
    "name": "Nguyễn Hoàng Bảo",
    "username": "bao1",
    "password": "bao",
    "newPassword": "bao"
}